//! 可执行文件探测：运行时、包管理器、Python 工具链、版本控制、容器。

use crate::model::{AppSettings, ExecutableInfo};
use crate::util;

struct Spec {
    name: &'static str,
    display: &'static str,
    category: &'static str,
    version_args: &'static [&'static str],
    /// PATH 之外需要额外搜索的目录
    extra_dirs: &'static [&'static str],
    used_by: &'static [&'static str],
    hint: &'static str,
}

const SPECS: &[Spec] = &[
    Spec {
        name: "node",
        display: "Node.js",
        category: "runtime",
        version_args: &["--version"],
        extra_dirs: &["%ProgramFiles%/nodejs", "%LOCALAPPDATA%/Programs/nodejs"],
        used_by: &["MCP (npx 型)", "npm 包管理", "Skills 依赖"],
        hint: "https://nodejs.org 或 winget install OpenJS.NodeJS.LTS",
    },
    Spec {
        name: "npm",
        display: "npm",
        category: "node-pm",
        version_args: &["--version"],
        extra_dirs: &["%ProgramFiles%/nodejs", "%APPDATA%/npm"],
        used_by: &["全局包管理", "MCP 安装"],
        hint: "随 Node.js 一同安装",
    },
    Spec {
        name: "npx",
        display: "npx",
        category: "node-pm",
        version_args: &["--version"],
        extra_dirs: &["%ProgramFiles%/nodejs"],
        used_by: &["MCP 免安装启动", "健康检查"],
        hint: "随 Node.js 一同安装",
    },
    Spec {
        name: "pnpm",
        display: "pnpm",
        category: "node-pm",
        version_args: &["--version"],
        extra_dirs: &["%APPDATA%/npm", "%LOCALAPPDATA%/pnpm"],
        used_by: &["全局包管理", "DSH Profile 依赖"],
        hint: "npm i -g pnpm 或 corepack enable",
    },
    Spec {
        name: "yarn",
        display: "Yarn",
        category: "node-pm",
        version_args: &["--version"],
        extra_dirs: &["%APPDATA%/npm"],
        used_by: &["全局包管理"],
        hint: "npm i -g yarn",
    },
    Spec {
        name: "bun",
        display: "Bun",
        category: "node-pm",
        version_args: &["--version"],
        extra_dirs: &["%USERPROFILE%/.bun/bin"],
        used_by: &["全局包管理"],
        hint: "https://bun.sh",
    },
    Spec {
        name: "uv",
        display: "uv",
        category: "python",
        version_args: &["--version"],
        extra_dirs: &["%USERPROFILE%/.local/bin", "%USERPROFILE%/.cargo/bin"],
        used_by: &["Python 环境创建", "uvx 型 MCP", "依赖锁定"],
        hint: "https://docs.astral.sh/uv 或 pip install uv",
    },
    Spec {
        name: "uvx",
        display: "uvx",
        category: "python",
        version_args: &["--version"],
        extra_dirs: &["%USERPROFILE%/.local/bin", "%USERPROFILE%/.cargo/bin"],
        used_by: &["Python MCP 免安装启动"],
        hint: "随 uv 一同安装",
    },
    Spec {
        name: "conda",
        display: "Conda",
        category: "python",
        version_args: &["--version"],
        extra_dirs: &[
            "%USERPROFILE%/anaconda3/Scripts",
            "%USERPROFILE%/miniconda3/Scripts",
            "%PROGRAMDATA%/anaconda3/Scripts",
            "%PROGRAMDATA%/miniconda3/Scripts",
            "%LOCALAPPDATA%/miniconda3/Scripts",
        ],
        used_by: &["Python 环境管理", "数据分析环境"],
        hint: "https://docs.conda.io 或安装 Miniconda",
    },
    Spec {
        name: "python",
        display: "Python",
        category: "python",
        version_args: &["--version"],
        extra_dirs: &[
            "%USERPROFILE%/anaconda3",
            "%PROGRAMDATA%/anaconda3",
            "%LOCALAPPDATA%/Programs/Python",
        ],
        used_by: &["脚本执行", "MCP (python 型)"],
        hint: "https://python.org 或 winget install Python.Python.3.12",
    },
    Spec {
        name: "pip",
        display: "pip",
        category: "python",
        version_args: &["--version"],
        extra_dirs: &["%USERPROFILE%/anaconda3/Scripts", "%PROGRAMDATA%/anaconda3/Scripts"],
        used_by: &["Python 依赖安装"],
        hint: "随 Python 一同安装",
    },
    Spec {
        name: "pipx",
        display: "pipx",
        category: "python",
        version_args: &["--version"],
        extra_dirs: &["%USERPROFILE%/.local/bin"],
        used_by: &["Python 工具隔离安装"],
        hint: "pip install --user pipx",
    },
    Spec {
        name: "git",
        display: "Git",
        category: "vcs",
        version_args: &["--version"],
        extra_dirs: &["%ProgramFiles%/Git/cmd", "%LOCALAPPDATA%/Programs/Git/cmd"],
        used_by: &["Skill Git 仓库同步", "备份"],
        hint: "https://git-scm.com 或 winget install Git.Git",
    },
    Spec {
        name: "docker",
        display: "Docker",
        category: "container",
        version_args: &["--version"],
        extra_dirs: &["%ProgramFiles%/Docker/Docker/resources/bin"],
        used_by: &["容器化 MCP"],
        hint: "https://docker.com（可选）",
    },
    /* -------------------------------------------------- Agent 命令行程序 */
    Spec {
        name: "opencode",
        display: "opencode",
        category: "agent-cli",
        version_args: &["--version"],
        extra_dirs: &["%APPDATA%/npm", "%PROGRAMDATA%/npm/npm", "%USERPROFILE%/.opencode/bin"],
        used_by: &["opencode Agent"],
        hint: "npm i -g opencode-ai",
    },
    Spec {
        name: "omp",
        display: "OhMyPi (omp)",
        category: "agent-cli",
        // omp 不带参数会进入交互式 TUI，因此只解析路径、不探测版本
        version_args: &[],
        extra_dirs: &["%LOCALAPPDATA%/omp"],
        used_by: &["oh-my-openagent Agent"],
        hint: "见 oh-my-openagent 安装说明",
    },
    Spec {
        name: "dsh",
        display: "DeepSeek Harness (dsh)",
        category: "agent-cli",
        version_args: &["--version"],
        extra_dirs: &["%APPDATA%/npm", "%PROGRAMDATA%/npm/npm"],
        used_by: &["DeepSeek Harness Agent"],
        hint: "npm i -g @deepseek-ai/dsh",
    },
    Spec {
        name: "claude",
        display: "Claude Code (claude)",
        category: "agent-cli",
        version_args: &["--version"],
        extra_dirs: &["%APPDATA%/npm", "%PROGRAMDATA%/npm/npm", "%USERPROFILE%/.local/bin"],
        used_by: &["Claude Code Agent"],
        hint: "npm i -g @anthropic-ai/claude-code",
    },
    Spec {
        name: "codex",
        display: "Codex CLI (codex)",
        category: "agent-cli",
        version_args: &["--version"],
        extra_dirs: &["%APPDATA%/npm", "%PROGRAMDATA%/npm/npm"],
        used_by: &["Codex Agent"],
        hint: "npm i -g @openai/codex",
    },
    Spec {
        name: "copilot",
        display: "GitHub Copilot CLI",
        category: "agent-cli",
        version_args: &["--version"],
        extra_dirs: &["%APPDATA%/npm", "%PROGRAMDATA%/npm/npm", "%LOCALAPPDATA%/Programs/copilot"],
        used_by: &["Copilot Agent"],
        hint: "npm i -g @github/copilot",
    },
    Spec {
        name: "gemini",
        display: "Gemini CLI",
        category: "agent-cli",
        version_args: &["--version"],
        extra_dirs: &["%APPDATA%/npm", "%PROGRAMDATA%/npm/npm"],
        used_by: &["Gemini Agent"],
        hint: "npm i -g @google/gemini-cli",
    },
    Spec {
        name: "aider",
        display: "Aider",
        category: "agent-cli",
        version_args: &["--version"],
        extra_dirs: &["%USERPROFILE%/.local/bin", "%USERPROFILE%/anaconda3/Scripts"],
        used_by: &["Aider Agent"],
        hint: "uv tool install aider-chat",
    },
];

pub fn scan(settings: &AppSettings) -> Vec<ExecutableInfo> {
    SPECS
        .iter()
        .map(|spec| {
            util::probe_executable(
                spec.name,
                spec.display,
                spec.category,
                spec.version_args,
                spec.extra_dirs,
                spec.used_by,
                spec.hint,
                &settings.executable_overrides,
            )
        })
        .collect()
}